=== xrowgmbh/xrowecommerce/unstable/buildtest/packages/ezpackage.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!ELEMENT packages (package*)>
<!ATTLIST packages
	vendor CDATA #REQUIRED
>
<!ELEMENT package (
    name,
	summary,
	description,
	vendor,
	type,
	ezpublish,
	maintainers,
	packaging,
	documents,
	changelog,
	simple-files,
	files,
	version,
	licence,
	state,
	dependencies,
	settings,
	install,
	uninstall)>
<!ATTLIST package
	version2 CDATA #REQUIRED
	development CDATA #REQUIRED
	is_active CDATA #REQUIRED
	install_type CDATA #REQUIRED
>
<!ELEMENT name (#PCDATA) >
<!ELEMENT summary (#PCDATA) >
<!ELEMENT description (#PCDATA) >
<!ELEMENT vendor (#PCDATA) >
<!ELEMENT type (#PCDATA) >
<!ATTLIST type
	value CDATA #REQUIRED
>
<!ELEMENT ezpublish (version,named-version) >
<!-- TWO version definitions should be fixed
	<!ELEMENT version (#PCDATA) >
-->
<!ELEMENT named-version (#PCDATA) >

<!ELEMENT maintainers (maintainer+) >
<!ELEMENT maintainer (name,email,role) >
<!ELEMENT email (#PCDATA) >
<!ELEMENT role (#PCDATA) >

<!ELEMENT packaging (timestamp,host) >
<!ELEMENT timestamp (#PCDATA) >
<!ELEMENT host (#PCDATA) >

<!ELEMENT documents (document+) >
<!ELEMENT document EMPTY >
<!ATTLIST document
	mime-type CDATA #REQUIRED
	name CDATA #REQUIRED
>
<!ELEMENT changelog (entry+) >
<!ELEMENT entry (change+)>
<!ATTLIST entry
	person CDATA #REQUIRED
	email CDATA #REQUIRED
	release CDATA #REQUIRED
>
<!ELEMENT change (#PCDATA)>

<!ELEMENT simple-files ANY>
<!ELEMENT files (collection+)>
<!ELEMENT collection (file-list+)>
<!ATTLIST collection
	name CDATA #REQUIRED
>
<!ELEMENT file-list (file+)>
<!ATTLIST file-list
	type CDATA #REQUIRED
	variable-name CDATA #REQUIRED
>
<!ELEMENT file EMPTY>
<!ATTLIST file
	name CDATA #REQUIRED
	md5sum CDATA #REQUIRED
>

<!ELEMENT version ANY>
<!ELEMENT number (#PCDATA)>
<!ELEMENT release (#PCDATA)>
<!ELEMENT licence (#PCDATA)>
<!ELEMENT state (#PCDATA)>
<!ELEMENT dependencies (provides,requires,obsoletes,conflicts)>
<!ELEMENT provides (provide*)>
<!ELEMENT requires (require*)>
<!ELEMENT require EMPTY>
<!ATTLIST require
	type CDATA #REQUIRED
	name CDATA #REQUIRED
	min-version CDATA #IMPLIED
	max-version CDATA #IMPLIED
>
<!ELEMENT obsoletes (obsolete*)>
<!ELEMENT conflicts (conflict*)>

<!ELEMENT settings (settings-file*)>
<!ELEMENT settings-file EMPTY>
<!ATTLIST settings-file
	filename CDATA #REQUIRED
>

<!ELEMENT install EMPTY>
<!ELEMENT uninstall EMPTY>

=== xrowgmbh/xrowecommerce/unstable/buildtest/packages/index.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE packages SYSTEM "ezpackage.dtd">
<?xml-stylesheet type="text/xsl" href="repository.xsl"?>
<packages vendor="xrow GmbH">
  <package name="ezgmaplocation_extension" version="1.0-0" type="extension" summary="ezgmaplocation extension" description="ezgmaplocation extension" url="http://packages.xrow.com/xrowecommerce/latest/ezgmaplocation_extension.ezpkg" thumbnail_url="http://packages.xrow.com/xrowecommerce/latest/thumbnails/ezgmaplocation_extension.png"/>
  <package name="ezwt_extension" version="1.1-0" type="extension" summary="ezwt extension" description="ezwt extension" url="http://packages.xrow.com/xrowecommerce/latest/ezwt_extension.ezpkg" thumbnail_url="http://packages.xrow.com/xrowecommerce/latest/thumbnails/ezwt_extension.png"/>
  <package name="ezstarrating_extension" version="1.0-0" type="extension" summary="ezstarrating extension" description="ezstarrating extension" url="http://packages.xrow.com/xrowecommerce/latest/ezstarrating_extension.ezpkg" thumbnail_url="http://packages.xrow.com/xrowecommerce/latest/thumbnails/ezstarrating_extension.png"/>
  <package name="ezjscore_extension" version="1.0-0" type="extension" summary="ezjscore extension" description="ezjscore extension" url="http://packages.xrow.com/xrowecommerce/latest/ezjscore_extension.ezpkg" thumbnail_url="http://packages.xrow.com/xrowecommerce/latest/thumbnails/ezjscore_extension.png"/>
  <package name="ezwebin_extension" version="1.5-0" type="extension" summary="ezwebin extension" description="ezwebin extension" url="http://packages.xrow.com/xrowecommerce/latest/ezwebin_extension.ezpkg" thumbnail_url="http://packages.xrow.com/xrowecommerce/latest/thumbnails/ezwebin_extension.png"/>
  <package name="xrowecommerce_extension" version="1.1-0" type="extension" summary="ezjscore extension" description="xrowecommerce extension" url="http://packages.xrow.com/xrowecommerce/latest/xrowecommerce_extension.ezpkg" thumbnail_url="http://packages.xrow.com/xrowecommerce/latest/thumbnails/xrowecommerce_extension.png"/>
  <package name="ezwebin_classes" version="1.5-0" type="contentclass" summary="ezwebin content classes" description="" url="http://packages.xrow.com/xrowecommerce/latest/ezwebin_classes.ezpkg" thumbnail_url="http://packages.xrow.com/xrowecommerce/latest/thumbnails/ezwebin_classes.png"/>
  <package name="xrowecommerce_classes" version="1.1-0" type="contentclass" summary="xrowecommerce content classes" description="" url="http://packages.xrow.com/xrowecommerce/latest/xrowecommerce_classes.ezpkg" thumbnail_url="http://packages.xrow.com/xrowecommerce/latest/thumbnails/ezwebin_classes.png"/>
  <package name="xrowecommerce_content" version="1.1-0" type="contentobject" summary="xrowecommerce content" description="" url="http://packages.xrow.com/xrowecommerce/latest/xrowecommerce_content.ezpkg" thumbnail_url="http://packages.xrow.com/xrowecommerce/latest/thumbnails/ezwebin_democontent.png"/>
  <package name="ezwebin_design_blue" version="1.5-0" type="sitestyle" summary="eZ Publish Website Interface design (blue)" description="This site style package contains the design for the Website Interface" url="http://packages.xrow.com/xrowecommerce/latest/ezwebin_design_blue.ezpkg" thumbnail_url="http://packages.xrow.com/xrowecommerce/latest/thumbnails/ezwebin_design.png"/>
  <package name="xrowecommerce_site" version="1.1-0" type="site" summary="xrow ecommerce" description="xrow E-Commerce is a web based e-commerce solution based on eZ Publish. It contains templates and settings that meets the most common requirements for an enterprise e-commerce website." url="http://packages.xrow.com/xrowecommerce/latest/xrowecommerce_site.ezpkg" thumbnail_url="http://packages.xrow.com/xrowecommerce/latest/thumbnails/xrowecommerce_site.png">
    <requires>
	  <require name="ezgmaplocation_extension" min-version="1.0" url="http://packages.xrow.com/xrowecommerce/latest/ezgmaplocation_extension.ezpkg"/>
      <require name="ezwt_extension" min-version="1.1" url="http://packages.xrow.com/xrowecommerce/latest/ezwt_extension.ezpkg"/>
      <require name="ezstarrating_extension" min-version="1.0" url="http://packages.xrow.com/xrowecommerce/latest/ezstarrating_extension.ezpkg"/>
      <require name="ezjscore_extension" min-version="1.0" url="http://packages.xrow.com/xrowecommerce/latest/ezjscore_extension.ezpkg"/>
	  <require name="ezwebin_extension" min-version="1.5" url="http://packages.xrow.com/xrowecommerce/latest/ezwebin_extension.ezpkg"/>
	  <require name="xrowecommerce_extension" min-version="1.1" url="http://packages.xrow.com/xrowecommerce/latest/xrowecommerce_extension.ezpkg"/>
	  <require name="ezwebin_classes" min-version="1.5" url="http://packages.xrow.com/xrowecommerce/latest/ezwebin_classes.ezpkg"/>
	  <require name="xrowecommerce_classes" min-version="1.1" url="http://packages.xrow.com/xrowecommerce/latest/xrowecommerce_classes.ezpkg"/>
	  <require name="xrowecommerce_content" min-version="1.1" url="http://packages.xrow.com/xrowecommerce/latest/xrowecommerce_content.ezpkg"/>
	  <require name="ezwebin_design_blue" min-version="1.5" url="http://packages.xrow.com/xrowecommerce/latest/ezwebin_design_blue.ezpkg"/>
    </requires>
  </package>
</packages>
